insidion_swagger_index:
    path:     /swagger/
    defaults: { _controller: InsidionSwaggerBundle:Swagger:index }

insidion_swagger_json:
    path:     /swagger/swagger.json
    defaults: { _controller: InsidionSwaggerBundle:Swagger:json }